# Generated by Django 3.0.6 on 2020-05-24 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_photo_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(default='avatar_hat.jpg', upload_to='images/projects/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(default='avatar_hat.jpg', upload_to='images/photos/%Y/%m/%d'),
        ),
    ]
